config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get 'homes/about' => 'homes#about', as: 'about'
  resources :comics, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
  resources :comic_comments, only: [:create, :destroy]
end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
end
    get 'search', to: 'searches#search', as: 'search'
     resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
  get 'chat/:id', to: 'chats#show', as: 'chat'
     resources :chats, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
   belongs_to :user
   belongs_to :room
end

app/models/comic.rb
class Comic < ApplicationRecord
  belongs_to :user
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  has_one_attached :image
  has_many :comic_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorites_users, through: :favorites, source: :user

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  # ソート機能
  scope :recent, -> { order(created_at: :desc) }

  def self.search_for(content, method)
    if method == 'perfect'
      Comic.where(title: content)
    elsif method == 'forward'
      Comic.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Comic.where('title LIKE ?', '%'+content)
    else
      Comic.where('title LIKE ?', '%'+content+'%')
    end
  end

end

app/models/comic_comment.rb
class ComicComment < ApplicationRecord
  belongs_to :user
  belongs_to :comic
  
  validates :comment, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :comic
  
  validates :comment, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :phone_number, :email, :message, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :comic
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms  #1つのルームにいるユーザ数は2人のためhas_manyになる
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comics, dependent: :destroy
  has_many :comic_comments, dependent: :destroy
  has_many :favorites_comics, through: :favorites, source: :comic
  has_many :favorites, dependent: :destroy
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_one_attached :profile_image
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,  length: {  maximum: 50 }



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
def follow(user)
  unless self == user
    self.relationships.find_or_create_by(followed_id: user.id)
  end
end
# フォローを外すときの処理
def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
end
# フォローしているか判定

def following?(user)
  followings.include?(user)
end
 def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
 end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    #BさんのUser情報を取得
   @user = User.find(params[:id])
  #user_roomsテーブルのuser_idがAさんのレコードのroom_idを配列で取得
   rooms = current_user.user_rooms.pluck(:room_id)
  #user_idがBさん(@user)で、room_idがAさんの属するroom_id（配列）となるuser_roomsテーブルのレコードを取得して、user_room変数に格納
  #これによって、AさんとBさんに共通のroom_idが存在していれば、その共通のroom_idとBさんのuser_idがuser_room変数に格納される（1レコード）。存在しなければ、nilになる。
   user_room = UserRoom.find_by(user_id: @user.id, room_id: rooms)
  #user_roomでルームを取得できなかった（AさんとBさんのチャットがまだ存在しない）場合の処理
   room = nil
   if user_room.nil?
   #roomのidを採番
    room = Room.new
    room.save
    #採番したroomのidを使って、user_roomのレコードを2人分（Aさん用、Ｂさん用）作る（＝AさんとBさんに共通のroom_idを作る）
    #Bさんの@user.idをuser_idとして、room.idをroom_idとして、UserRoomモデルのがラムに保存（1レコード）
     UserRoom.create(user_id: @user.id, room_id: room.id)
    #Aさんのcurrent_user.idをuser_idとして、room.idをroom_idとして、UserRoomモデルのカラムに保存（1レコード）
     UserRoom.create(user_id: current_user.id, room_id: room.id)
   else
    #user_roomに紐づくroomsテーブルのレコードをroomに格納
     room = user_room.room
   end

   #roomに紐づくchatsテーブルのレコードを@chatsに格納
    @chats = room.chats
   #form_withでチャットを送信する際に必要な空のインスタンス
   #ここでroom.idを@chatに代入しておかないと、form_withで記述するroom_idに値が渡らない
    @chat = Chat.new(room_id: room.id)
  end
  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    #["選択して下さい"], ["少年"], ["少女"],  ["青年"], ["女性"],["BL"]]
    #@comics1 = Comic.where(genre: '少年')
    #@comics2 = Comic.where(genre: '少女')
    #@comics3 = Comic.where(genre: '青年')
    #@comics4 = Comic.where(genre: '女性')
    #@comics5 = Comic.where(genre: 'BL')
    @ranks = Comic.joins(:favorites).group(:id).order("count(favorites.comic_id) desc").first(5)
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :ensure_correct_user, only: [:edit, :update]
    def show
        @comic = Comic.new
        @user = User.find(params[:id])
        @comics = @user.comics
        @comics = @user.comics.page(params[:page])
        
    end
    def index
         @comic = Comic.new
         @users = User.all.page(params[:page])
    end
    def edit
        @user = User.find(params[:id])
    end
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
        redirect_to user_path(@user), notice: "You have updated user successfully."
        else
        render "edit"
        end
    end

    def user_params
        params.require(:user).permit(:name, :introduction, :profile_image)
    end
    def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/create.js.erb
/*.messageを部分更新。appendメソッドで要素を追加 */
$('.message').append("<p style='text-align: left;'><%= @chat.message %></p>");

/*チャット投稿後、フォームの値に前回の投稿内容が残らないようにする */
$('input[type=text]').val("")

app/views/chats/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-6">
            <h2>チャット <%= @user.name %></h2>

            <table class="message table">
              <thead>
                <tr>
                  <th style="text-align: left; font-size: 20px;"><%= current_user.name %></th>
                  <th style="text-align: right; font-size: 20px;"><%= @user.name %></th>
                </tr>
              </thead>
              <% @chats.each do |chat| %>
                <% if chat.user_id == current_user.id %>
                <tbody>
                  <tr>
                    <th>
                      <p style="text-align: left;"><%= chat.message %></p>
                    </th>
                    <th></th>
                  </tr>
                <% else %>
                  <tr>
                    <th></th>
                    <th>
                      <p style="text-align: right;"><%= chat.message %></p>
                    </th>
                  </tr>
                </tbody>
                <% end %>
              <% end %>
            </table>

            <%= form_with model: @chat, remote: true do |f| %>
              <%= f.text_field :message %>
              <%= f.hidden_field :room_id %>
              <%= f.submit "送信", class:"btn btn-sm btn-success chat-btn" %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>画像</th>
      <th>名前</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
         <td>フォロー数</td>
        <td><%= link_to user.followings.count, user_followings_path(user.id) %></td>
        <td>フォロワー数</td>
        <td><%= link_to user.followers.count, user_followers_path(user.id) %></td>
        <% if current_user.following?(user) %>
        <td><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></td>
        <% else %>
        <td><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
        <% end %>
        <td><%= link_to '詳細', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>名前</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>紹介</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>フォロー</th>
	  <td><%= link_to user.followings.count, user_followings_path(user.id) %></td>
  </tr>
  <tr>
    <th>フォロワー</th>
     <td><%= link_to user.followers.count, user_followers_path(user.id) %></td>
  </tr>
</table>
<div class='row'>
  <% if user != current_user %>
  <% if current_user.following?(user) %>
  <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete,class:"btn btn-primary" %>
  <% else %>
  <%= link_to "フォローする", user_relationships_path(user.id), method: :post,class:"btn btn-success" %>
    <% end %>
  <% else %>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
  <% end %>
  <!-- current_userと@userが一致していないかつフォローしている時に`Begin Chat`を表示 -->

  <% if current_user != user && current_user.following?(user)%>
   <%= link_to 'チャット', chat_path(user.id),class: "btn btn-warning" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>ユーザー情報</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :名前 %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :画像 %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :紹介 %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit :更新, class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>ユーザー情報</h2>
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">新規投稿</h2>
      <%= render 'comics/form', comic: @comic %>
      </div>
      <div class='col-md-8 offset-md-1'>
      <h2>ユーザー</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center"><%= paginate @users %></div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>ユーザー情報</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">新規投稿</h2>
      <%= render 'comics/form', comic: @comic %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>漫画</h2>
      <%= render 'comics/index',comics: @comics %>
    </div>
  </div>
</div>