config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get 'homes/about' => 'homes#about', as: 'about'
  resources :comics, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
  resources :comic_comments, only: [:create, :destroy]
end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
end
    get 'search', to: 'searches#search', as: 'search'
     resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
  get 'chat/:id', to: 'chats#show', as: 'chat'
     resources :chats, only: [:create]
end

app/models/comic.rb
class Comic < ApplicationRecord
  belongs_to :user
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  has_one_attached :image
  has_many :comic_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorites_users, through: :favorites, source: :user

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  # ソート機能
  scope :recent, -> { order(created_at: :desc) }

  def self.search_for(content, method)
    if method == 'perfect'
      Comic.where(title: content)
    elsif method == 'forward'
      Comic.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Comic.where('title LIKE ?', '%'+content)
    else
      Comic.where('title LIKE ?', '%'+content+'%')
    end
  end

end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController

  before_action :correct_user, only: [:edit, :update]

  def show
    @comic = Comic.find(params[:id])
    @user = @comic.user
    @newcomic = Comic.new
    @comic_comment = ComicComment.new
    @comments = @comic.comic_comments
  end
  def index
    @comic = Comic.new
    @comics = Comic.left_joins(:favorites).group(:id).order("count(favorites.comic_id) desc").page(params[:page])
    # ソート機能
    if params[:sort] == "new_arrival_order"
      @comics = Comic.page(params[:page]).order(created_at: :desc)
    elsif params[:sort] == "posting_order"
      @comics = Comic.page(params[:page]).order(created_at: :asc)
    elsif params[:sort] == "highly_rated"
      @comics = Comic.page(params[:page]).order(rate: :desc)
    elsif params[:sort] == "low_rating"
      @comics = Comic.page(params[:page]).order(rate: :asc)
    else
      @comics = Comic.left_joins(:favorites).group(:id).order("count(favorites.comic_id) desc").page(params[:page])
    end
    #@comics = Comic.all
    #@comics = Comic.page(params[:page]).reverse_order
    #@comics = Comic.includes(:favorites_users).sort {|a,b| b.favorites_users.size <=> a.favorites_users.size}
    #binding.pry
    #@comics.page(params[:page]).reverse_order

  end
  def create
    @comic = Comic.new(comic_params)
    @comic.user_id = current_user.id
    if @comic.save
      redirect_to comic_path(@comic), notice: "You have created book successfully."
    else
      @comics = Comic.page(params[:page]).reverse_order
      render 'index'
    end
  end
  def edit
    @comic = Comic.find(params[:id])
    redirect_to comics_path unless current_user.id == @comic.user_id
  end
  def update
    @comic = Comic.find(params[:id])
    if @comic.update(comic_params)
      redirect_to comic_path(@comic), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @comic = Comic.find(params[:id])
    @comic.destroy
    redirect_to comics_path
  end

  private

  def comic_params
    params.require(:comic).permit(:title, :body, :genre, :rate)
  end

  def correct_user
    @comic = Comic.find(params[:id])
    redirect_to(comics_path) unless @comic.user == current_user
  end
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/comics/_form.html.erb
<%= form_with model: comic,local:true do |f| %>
  <div class="form-group">
    <%= f.label :タイトル %>
    <%= f.text_field :title, class: 'form-control comic_title' %>
  </div>
  <div class="form-group">
    <%= f.label :ジャンル %>
    <%= f.select :genre, options_for_select([["選択して下さい"], ["少年"], ["少女"],  ["青年"], ["女性"],["BL"]]) %>
  </div>
  <div class="form-group">
    <%= f.label :説明 %>
    <%= f.text_area :body, class: 'form-control comic_body' %>
  </div>
  <!--評価-->
  <div class="form-group" id="star">
    <%= f.label :評価 %>
    <%= f.hidden_field :rate, id: :review_star, class:'form-control' %>
  </div>
  <!--評価javascript-->
    <script>
    $(document).on('turbolinks:load', function() {
      $('#star').empty();
      $('#star').raty({
        size     : 36,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'comic[rate]',
        half: true,
      });
    })
    </script>


  <div class="form-group">
    <%= f.submit :投稿, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/comics/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>タイトル</th>
      <th>説明</th>
      <th>ジャンル</th>
      <th>評価</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% comics.each do |comic| %>
      <tr>
        <td><%= link_to(comic.user) do %>
          <%= image_tag comic.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to comic.title,comic, class: "comic_#{comic.id}" %></td>
        <td><%= comic.body %></td>
        <td><%= comic.genre %></td>
        <td class="review-td"><%= render "comics/static_rate", comic: comic %></td>
        <td id="favorite_buttons_<%= comic.id %>">
          <%= render "favorites/favorites", comic: comic %>
        </td>
        <td><%= link_to "#{comic.comic_comments.count} コメント", comic_path(comic.id) %></td>
      </tr>
         <% end %>
  </tbody>
</table>

app/views/comics/_static_rate.html.erb
<div class="rate_<%= comic.id %>" class="form-group">
</div>
    <script>
    $(document).on('turbolinks:load', function() {
      $('.rate_<%= comic.id %>').empty();
      $('.rate_<%= comic.id %>').raty({
        size     : 36,
        readOnly: true,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        score: '<%= comic.rate %>',
        half: true,
      });
    })
    </script>

app/views/comics/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>編集</h1>
  		<% if @comic.errors.any? %>
      <%= @comic.errors.count %> error prohibited this obj from being saved:
      <% @comic.errors.full_messages.each do |message| %>
      %= message %>
      <% end %>
      <% end %>
    		<%= render 'form', comic: @comic %>
    		<%= link_to '詳細', @comic, class: "comic_#{@comic.id}" %> |
    		<%= link_to 'バック', comics_path, class: "back" %>
  	</div>
  </div>
</div>

app/views/comics/index.html.erb
 <div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
          <h2>ユーザー情報</h2>
          <% if @comic.errors.any? %>
          <%= @comic.errors.count %> error prohibited this obj from being saved:
          <% @comic.errors.full_messages.each do |message| %>
          <%= message %>
          <% end %>
          <% end %>
          <%= render 'users/info', user: current_user %>
           <h2 class="mt-3">新規投稿</h2>
            <%= render 'form', comic: @comic %>
    </div>
      <div class='col-md-8 offset-md-1'>
            <h2>漫画</h2>
              <span><%= link_to "新着順",comics_path(sort: "new_arrival_order"), class: "btn btn-sm btn-link" %></span>
              <span><%= link_to "投稿順",comics_path(sort: "posting_order"), class: "btn btn-sm btn-link" %></span>
              <span><%= link_to "高評価",comics_path(sort: "highly_rated"), class: "btn btn-sm btn-link" %></span>
              <span><%= link_to "低評価",comics_path(sort: "low_rating"), class: "btn btn-sm btn-link" %></span>
            <%= render 'index', comics: @comics%>
      </div>
  </div>
 </div>
 <div class="d-flex justify-content-center"><%= paginate @comics %></div>

app/views/comics/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
        <h2>ユーザー情報</h2>
        <%= render 'users/info', user: current_user %>
        <h2 class="mt-3">新規投稿</h2>
        <%= render 'form', comic: @newcomic %>
    </div>
      <div class='col-md-8 offset-md-1'>
        <h2>漫画 詳細</h2>
    		<table class='table'>
    		 <tr>
    		<td><%= link_to(@comic.user) do %>
            <%= image_tag @comic.user.get_profile_image, size:"100x100" %><br>
            <%= @comic.user.name %>
            <% end %>
            </td>
            <td><%= link_to @comic.title, @comic %></td>
            <td><%= @comic.body %></td>
            <td><%= @comic.genre %></td>
            <!--星形レビュー-->
            <td class="review-td"><%= render "static_rate", comic: @comic %></td>
            <td id="favorite_buttons_<%= @comic.id %>">
              <%= render "favorites/favorites", comic: @comic %>
            </td>
            <% if @comic.user == current_user %>
            <td><%= link_to '編集', edit_comic_path(@comic), class: "btn btn-sm btn-success edit_comic_#{@comic.id}" %></td>
            <td><%= link_to '削除', comic_path(@comic), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_comic_#{@comic.id}"%></td>
            <% end %>
         </tr>
        </table>
      <div>
        <p>コメント件数：
          <span id="num_of_comments">
            <%= @comic.comic_comments.count %>
          </span>
        </p>
        <div id="commentOutline">
          <%= render partial: "comic_comments/comment", locals: { comic: @comic }%>
        </div>
      </div>
          <div>
          <%= form_with(model:[@comic, @comic_comment], local: false) do |f| %>
            <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", id: "inputComment" %>
            <%= f.submit "送信する" %>
          <% end %>
          </div>
    </div>
  </div>
</div>