config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get 'homes/about' => 'homes#about', as: 'about'
  resources :comics, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
  resources :comic_comments, only: [:create, :destroy]
end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
end
    get 'search', to: 'searches#search', as: 'search'
     resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
  get 'chat/:id', to: 'chats#show', as: 'chat'
     resources :chats, only: [:create]
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :phone_number, :email, :message, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!, except: [:new]
  
  def new
    @contact = Contact.new
  end

  # 確認画面を作成する場合はこのような記述になるかと思います。
  # newアクションから入力内容を受け取り、
  # 送信ボタンを押されたらcreateアクションを実行します。
  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render :new
    end
  end
  # 入力内容に誤りがあった場合、
  # 入力内容を保持したまま前のページに戻るのが当たり前になっているかと思いますが、
  # backアクションを定義することで可能となります。
  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  # 実際に送信するアクションになります。
  # ここで初めて入力内容を保存します。
  # セキュリティーのためにも一定時間で入力内容の削除を行ってもいいかもしれません。
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_path
    else
      render :new
    end
  end

  # 送信完了画面を使用する場合お使いください。
  def done
    
  end

  private

  def contact_params
    params.require(:contact)
          .permit(:email,
                  :name,
                  :phone_number,
                  :subject,
                  :message
                 )
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/confirm.html.erb
<table>
  <tbody>
    <tr>
      <td class="text-center" style="width: 30%;">お名前</td>
      <td><%= @contact.name %></td>
    </tr>
    <tr>
      <td class="text-center">メッセージ</td>
      <td style="white-space: pre-wrap;"><%= @contact.message %></td>
    </tr>
  </tbody>
</table>
<%= form_for(@contact) do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :phone_number %>
  <%= f.hidden_field :subject %>
  <%= f.hidden_field :message %>
  <div><%= f.submit '送信' %></div>
<% end %>
<%= form_for @contact, url: back_path do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :phone_number %>
  <%= f.hidden_field :subject %>
  <%= f.hidden_field :message %>
  <div><%= f.submit '入力画面に戻る' %></div>
<% end %>

app/views/contacts/done.html.erb
<h2>お問い合わせ完了しました。</h2>

app/views/contacts/new.html.erb
<div class='container px-5 px-sm-0'>
  <h3>【お問い合わせフォーム】</h3>
      <%= form_for(@contact, url: confirm_path) do |f| %>
      <%= render "layouts/errors", obj: @contact %>
    <div class="form-group">
      <%= f.label :name, 'お名前*' %>
      <%= f.text_field :name, autofocus: true, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :email, 'メールアドレス' %>
      <%= f.text_field :email, autofocus: true, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :phone_number, '電話番号' %>
      <%= f.text_field :phone_number, autofocus: true, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :message, 'お問い合わせ内容' %>
      <%= f.text_area :message, size: '10x10', class: 'form-control' %>
    </div>

    <div>
      <%= f.submit '送信' %>
    </div>
  <% end %>
</div>